# Generated by Django 3.2.7 on 2021-10-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
