# Generated by Django 3.2.7 on 2021-10-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypost',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
