# Generated by Django 3.2.8 on 2021-11-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211117_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='startdate',
            field=models.DateTimeField(),
        ),
    ]
