# Generated by Django 3.2.8 on 2021-10-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_storypost_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_name', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['interest_name'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=40)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['startdate'],
            },
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_name', models.CharField(max_length=40)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['startdate'],
            },
        ),
    ]
