# Generated by Django 3.2.8 on 2021-11-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_education_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypost',
            name='pict',
            field=models.ImageField(default=None, upload_to='pics/'),
        ),
    ]
